data:
    name: 'aachen'
    load_db: false
    load_queries: true
    resize_max: 1920
    grayscale: true
model:
    name: 'hf_net'
    image_channels: 1
    local:
        detector_threshold: 0.005
        nms_radius: 4
        num_keypoints: 2500
